[package]
name = "create-do-firewall-wasm"
version = "0.0.7"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
http = "0.2"
wasi-experimental-http = "0.10"

[[bin]]
name = "module"
path = "src/main.rs"
