[package]
name = "create-do-firewall-wasm"
version = "0.0.7"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "module"
path = "src/main.rs"
